### PR TITLE
add text classification notebook compatible with bigdl-0.3

### PR DESCRIPTION
**Pull request by megaSpoon**

### CODE REVIEW

**Comment by megaSpoon** [comment]
related to https://github.com/intel-analytics/BigDL/issues/1761

**Comment by jason-dai** [comment]
@zhichao-li @psyyz10 please take a look

**Comment by psyyz10** [comment]
The link [https://github.com/intel-analytics/analytics-zoo/blob/f19f9d845076b2c9bad080db27ae14e5ec6f04f2/apps/simpleTextClassification/text_classfication.ipynb](https://github.com/intel-analytics/analytics-zoo/blob/f19f9d845076b2c9bad080db27ae14e5ec6f04f2/apps/simpleTextClassification/text_classfication.ipynb) is not exist

**Comment by megaSpoon** [comment]
@psyyz10  Do you mean the link to the notebook does not exist? It's strange because it can be opened and shown on my browser.

**Comment by psyyz10** [comment]
@megaSpoon sorry, I copid the wrong link, I mean the link [https://github.com/intel-analytics/BigDL/tree/branch-0.1/pyspark/dl/models/textclassifier](https://github.com/intel-analytics/BigDL/tree/branch-0.1/pyspark/dl/models/textclassifier) does not exist

**Pull request closed without merging**
