### PR TITLE
Bigdl-nano datasets, models and transforms

### PR DESCRIPTION
**Pull request by leonardozcm**

### CODE REVIEW

**Comment by yangw1234** [comment]
adding license？

**Comment by yangw1234** [comment]
there is also some updates on transforms.

**Comment by jason-dai** [comment]
```
nano\pytorch\vision\transforms
nano\pytorch\vision\datasets
nano\pytorch\vision\models
```

**Comment by leonardozcm** [comment]
clear, file tree:
```
(test37) root@3659e767d1ab:~/analytics-zoo/python/nano/src/bigdl# tree
.
`-- nano
    |-- __init__.py
    |-- common
    |   |-- __init__.py
    |   |-- common.py
    |   |-- cpu_schedule.py
    |   |-- init_nano.py
    |   `-- test_cpu.sh
    |-- pytorch
    |   |-- __init__.py
    |   |-- accelerators
    |   |   |-- __init__.py
    |   |   `-- ipex_accelerator.py
    |   |-- plugins
    |   |   |-- __init__.py
    |   |   |-- ddp_spawn.py
    |   |   |-- environments
    |   |   |   |-- __init__.py
    |   |   |   `-- ray_envbase.py
    |   |   `-- ray_distributed.py
    |   |-- trainer
    |   |   |-- Trainer.py
    |   |   `-- __init__.py
    |   `-- vision
    |       |-- datasets
    |       |   |-- __init__.py
    |       |   `-- datasets.py
    |       |-- models
    |       |   |-- __init__.py
    |       |   |-- _utils.py
    |       |   |-- classifier.py
    |       |   `-- vision.py
    |       `-- transforms
    |           |-- __init__.py
    |           |-- transforms.py
    |           `-- transforms_seg_n_detect.py
    `-- tf
        |-- __init__.py
        `-- keras
            |-- Model.py
            |-- Sequential.py
            `-- __init__.py

13 directories, 29 files
```

**Comment by yangw1234** [comment]
LGTM

**Pull request merged**
