### PR TITLE
Integration tf1.0

### PR DESCRIPTION
**Pull request by leonardozcm**
Jenkins validation for **tf1.0** integration test.

### CODE REVIEW

**Comment by yangw1234** [comment]
change file name to `run-example-tests-yarn-integration.sh` ?

**Comment by leonardozcm** [comment]
> change file name to `run-example-tests-yarn-integration.sh` ?

ok，renamed.

**Comment by leonardozcm** [comment]
jenkins passed http://10.239.47.210:18888/job/ZOO-PR-Python-integration-test/32/ @yangw1234

**Comment by yangw1234** [comment]
LGTM

**Pull request merged**
