### PR TITLE
update bigdl version to 0.14.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by Le-Zheng**

### CODE REVIEW

**Comment by Le-Zheng** [comment]
with latest BigDL-core 0.14.0-snapshot https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/core/ and BigDL 0.14.0-snapshot https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/
zoo pr validation http://10.112.231.51:18888/job/ZOO-PR-Validation/

**Comment by jason-dai** [comment]
This is confusing - both BigDL master and BigDL branch are 0.14.0-snapshot? @glorysdj @Le-Zheng

**Comment by Le-Zheng** [comment]
> This is confusing - both BigDL master and BigDL branch are 0.14.0-snapshot? @glorysdj @Le-Zheng

BigDL master and branch 2.0 release could be distinguished with different artifact id on maven? @glorysdj BigDL master released `bigdl-SPARK_3.1`, `bigdl-SPARK_2.4`.
Branch 2.0 release `bigdl-dllib-spark_3.1.2`, `bigdl-orca-spark_3.1.2`, `bigdl-serving-spark_3.1.2`, etc

**Comment by jason-dai** [comment]
> > This is confusing - both BigDL master and BigDL branch are 0.14.0-snapshot? @glorysdj @Le-Zheng
> 
> BigDL master and branch 2.0 release could be distinguished with different artifact id on maven? @glorysdj BigDL master released `bigdl-SPARK_3.1`, `bigdl-SPARK_2.4`. Branch 2.0 release `bigdl-dllib-spark_3.1.2`, `bigdl-orca-spark_3.1.2`, `bigdl-serving-spark_3.1.2`, etc

This is still confusing as users may think bigdl-0.14.0 is a superset of `bigdl-dllib-0.14.0`; you need give them different versions

**Comment by Le-Zheng** [comment]
> > > This is confusing - both BigDL master and BigDL branch are 0.14.0-snapshot? @glorysdj @Le-Zheng
> > 
> > 
> > BigDL master and branch 2.0 release could be distinguished with different artifact id on maven? @glorysdj BigDL master released `bigdl-SPARK_3.1`, `bigdl-SPARK_2.4`. Branch 2.0 release `bigdl-dllib-spark_3.1.2`, `bigdl-orca-spark_3.1.2`, `bigdl-serving-spark_3.1.2`, etc
> 
> This is still confusing as users may think bigdl-0.14.0 is a superset of `bigdl-dllib-0.14.0`; you need give them different versions

Shall we keep BigDL master as 0.14.0-snapshot and rename BigDL branch 2.0 to another version name?

**Comment by glorysdj** [comment]
shall we use bigdl-2.0-SNAPSHOT(2.1, 2.2 etc) to distinguish from bigdl 1.0?
or
use bigdl-0.13.1 to keep bigdl 1.0 versions and start from 0.14.+ for bigdl 2.0 versions?

**Comment by jason-dai** [comment]
> shall we use bigdl-2.0-SNAPSHOT(2.1, 2.2 etc) to distinguish from bigdl 1.0? or use bigdl-0.13.1 to keep bigdl 1.0 versions and start from 0.14.+ for bigdl 2.0 versions?

We should use 0.13 for master

**Comment by glorysdj** [comment]
> > shall we use bigdl-2.0-SNAPSHOT(2.1, 2.2 etc) to distinguish from bigdl 1.0? or use bigdl-0.13.1 to keep bigdl 1.0 versions and start from 0.14.+ for bigdl 2.0 versions?
> 
> We should use 0.13 for master

ok, we will use 0.13.1-SNAPSHOT for master branch since 0.13.0 is released.

**Comment by jason-dai** [comment]
> > > shall we use bigdl-2.0-SNAPSHOT(2.1, 2.2 etc) to distinguish from bigdl 1.0? or use bigdl-0.13.1 to keep bigdl 1.0 versions and start from 0.14.+ for bigdl 2.0 versions?
> > 
> > 
> > We should use 0.13 for master
> 
> ok, we will use 0.13.1-SNAPSHOT for master branch since 0.13.0 is released.

Actually I think we should only update branch-0.13, not master

**Comment by glorysdj** [comment]
> > > > shall we use bigdl-2.0-SNAPSHOT(2.1, 2.2 etc) to distinguish from bigdl 1.0? or use bigdl-0.13.1 to keep bigdl 1.0 versions and start from 0.14.+ for bigdl 2.0 versions?
> > > 
> > > 
> > > We should use 0.13 for master
> > 
> > 
> > ok, we will use 0.13.1-SNAPSHOT for master branch since 0.13.0 is released.
> 
> Actually I think we should only update branch-0.13, not master

OK, get it. We will update branch-0.13.

**Pull request merged**
