### PR TITLE
change all labels_cols to label_cols in orca

### PR DESCRIPTION
**Pull request by yangw1234**

### CODE REVIEW

**Comment by jason-dai** [comment]
Also need to update the documents in https://github.com/intel-analytics/analytics-zoo/tree/master/readthedocs/source

**Comment by yangw1234** [comment]
> Also need to update the documents in https://github.com/intel-analytics/analytics-zoo/tree/master/readthedocs/source

Yeah, they have been changed. I searched globally in the project and leave only the ones in TFPark. There is only one reference in the readthedocs directory, see the last file.

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/4930/ jenkins passed except for a few failures related to jenkins

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/4930/ jenkins passed except for a few failures related to jenkins

**Pull request merged**
