### PR TITLE
Add summary for Keras Models

### PR DESCRIPTION
**Pull request by hkvision**
Fix https://github.com/intel-analytics/zoo/issues/193

For a model
```
    val model = Sequential[Float]()
    model.add(Embedding[Float](20000, 128, inputShape = Shape(100)).setName("embedding1"))
    model.add(Dropout[Float](0.25))
    model.add(Convolution1D[Float](nbFilter = 64, filterLength = 5, borderMode = "valid",
      activation = "relu", subsampleLength = 1).setName("conv1"))
    model.add(MaxPooling1D[Float](poolLength = 4))
    model.add(LSTM[Float](70))
    model.add(Dense[Float](1).setName("dense1"))
    model.add(Activation[Float]("sigmoid"))
    model.freeze("dense1")
    model.summary()
```
`model.summary()` will print:
```
------------------------------------------------------------------------------------------------------------------------
Layer (type)                            Output Shape              Param #       Connected to                          
========================================================================================================================
Inputa2e0d7f4 (Input)                   (None, 100)               0                                                   
________________________________________________________________________________________________________________________
embedding1 (Embedding)                  (None, 100, 128)          2560000       Inputa2e0d7f4                         
________________________________________________________________________________________________________________________
Dropout30e47a22 (Dropout)               (None, 100, 128)          0             embedding1                            
________________________________________________________________________________________________________________________
conv1 (Convolution1D)                   (None, 96, 64)            41024         Dropout30e47a22                       
________________________________________________________________________________________________________________________
MaxPooling1D334225f5 (MaxPooling1D)     (None, 24, 64)            0             conv1                                 
________________________________________________________________________________________________________________________
LSTM729dd812 (LSTM)                     (None, 70)                37800         MaxPooling1D334225f5                  
________________________________________________________________________________________________________________________
dense1 (Dense)                          (None, 1)                 71            LSTM729dd812                          
________________________________________________________________________________________________________________________
Activation48351151 (Activation)         (None, 1)                 0             dense1                                
________________________________________________________________________________________________________________________
Total params: 2,638,895
Trainable params: 2,638,824
Non-trainable params: 71
------------------------------------------------------------------------------------------------------------------------
```
This will be exactly the same as Keras.

### CODE REVIEW

**Comment by dding3** [comment]
For the Param column, can we print sizes eg. batch x inputSize x outputSize?

**Comment by hkvision** [comment]
@dding3 I'm OK with both options, I choose to print out the total param number because Keras exactly behaves like this.

**Comment by jason-dai** [comment]
Let's keep Keras style and merge it for now.

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/job/ZOO-PR-Validation/544/

**Pull request merged**
