### PR TITLE
fix tf_lenent_mnist notebook

### PR DESCRIPTION
**Pull request by Le-Zheng**

### CODE REVIEW

**Comment by Le-Zheng** [comment]
fix https://github.com/intel-analytics/analytics-zoo/issues/3359

**Comment by Le-Zheng** [comment]
@jason-dai  It takes 2min30s~3min to install Java 8 and python dependencies. And takes almost 2 min to run the program( epoch = 1, 98% acc).
I tried to set batch size to 320*4. It only reduces 13s for one epoch and obtains 95.6% acc.

**Comment by jason-dai** [comment]
> @jason-dai It takes 2min30s~3min to install Java 8 and python dependencies. And takes almost 2 min to run the program( epoch = 1, 98% acc).
> I tried to set batch size to 320*4. It only reduces 13s for one epoch and obtains 95.6% acc.

is It running with 4 cores? I saw a message saying thread pool is 1

**Comment by Le-Zheng** [comment]
> > @jason-dai It takes 2min30s~3min to install Java 8 and python dependencies. And takes almost 2 min to run the program( epoch = 1, 98% acc).
> > I tried to set batch size to 320*4. It only reduces 13s for one epoch and obtains 95.6% acc.
> 
> is It running with 4 cores? I saw a message saying thread pool is 1

It seems "cpu cores	: 1" on colab.

**Comment by jason-dai** [comment]
LGTM

**Pull request merged**
