### PR TITLE
add tfpark example readme

### LINKED ISSUE #1365: No README for tensorflow/tfpark examples

### PR DESCRIPTION
**Pull request by yangw1234**
fix #1365

### CODE REVIEW

**Comment by dding3** [comment]
Seems the instructions are for `Run with prebuilt package`, do we need add `Run after pip install`, eg: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/textclassification/README.md

**Comment by yangw1234** [comment]
@dding3  added `run after pip install`

**Comment by yangw1234** [comment]
jenkins pass http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/2306/ except one unrelated fail which passed in http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/2307/

**Comment by dding3** [comment]
Seems there are 3 examples in the readme, it would be great if we can have some explanations for each example and give some explanations for the output.

**Comment by dding3** [comment]
Also it would be great if we can give some guidances about where to download the python example (eg. estimator_inception.py). And provide script on how to clone `slim` library and add them to `PYTHONPATH` in the README

**Pull request merged**
