### PR TITLE
Fix AutoXGBoostClassifier SkOpt Example Recipe Parametters

### PR DESCRIPTION
**Pull request by PeterQiu0516**
Fix issue #3685.
Pass parameters into the SkOpt Recipe.

### CODE REVIEW

**Comment by PeterQiu0516** [comment]
Jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation-Spark-2.4/3661/

**Comment by yushan111** [comment]
> Jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation-Spark-2.4/3661/

You should run http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/

**Comment by PeterQiu0516** [comment]
Jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation/5308/

**Comment by PeterQiu0516** [comment]
Jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation/5318/

**Pull request merged**
