### PR TITLE
add --batch_size option

### PR DESCRIPTION
**Pull request by zzti-bsj**
## add `--batch_size` option

please reference to this [commit](https://github.com/intel-analytics/analytics-zoo/commit/86c2ff6974b42f49ca9aac23d492b5d085bcf472) for all changes.

### CODE REVIEW

**Review by glorysdj — APPROVED** [review]
LGTM

**Comment by glorysdj** [comment]
please run pr validation

**Comment by zzti-bsj** [comment]
pr validation passed!

**Comment by glorysdj** [comment]
> pr validation passed!

plase also paste the link here

**Comment by zzti-bsj** [comment]
here is [pr validation link](http://10.239.176.111:18888/view/ZOO-PR/job/ZOO-PR-Validation/5670/)

**Pull request merged**
