### PR TITLE
Support creating a ImageSet from a folder of images

### PR DESCRIPTION
**Pull request by yangw1234**

### CODE REVIEW

**Comment by yangw1234** [comment]
jenkins pass http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/2146/?auto_refresh=true

**Comment by dding3** [comment]
Seems like `fromImageFolder` doesn't support read from hdfs folder, I think we need support that. 

More importantly, seems like there are lots of duplicate code of `fromImageFolder` with `ImageSet.read` and the difference is `fromImagaeFolder` supports read `label`. And it may be bring confusion. Can we add this feature to `ImageSet.read`? eg. add a sth like `readLabel` param in `ImageSet.read` to support read label?

**Comment by yangw1234** [comment]
Per discussion with @dding3 offline, I will change `fromImageFolder` to `readWithLabel` and hdfs support will be added in the next PR.

**Comment by jason-dai** [comment]
I think we should add this functionality to `ImageSetr.read`

**Comment by yangw1234** [comment]
@jason-dai as discussed with @dding3 , `readWithLabel` should return a `LabelMap` to tell the called which class maps to which label (for example we have folder cats and folder dogs, label map tells user whether cats is 1 and dogs is 2 or dogs is 1 and cats is 2). This will change the signature of the ImageSet.read, thus we decided to add another method.

**Comment by yangw1234** [comment]
@jason-dai @dding3 I have a another idea. Add a `labelMap` field in ImageSet and pass in the labelMap to ImageSet through constructor. Is that ok?

**Comment by yangw1234** [comment]
1. Moved this functionality to `ImageSet.read`
2. Added a `labelMap` field in ImageSet.
3. Added HDFS support

**Comment by yangw1234** [comment]
test hdfs manually

**Comment by yangw1234** [comment]
jenkins pass http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/2149/

**Comment by yangw1234** [comment]
I'll merge it first as there are little public api changes and my next pr depends on this. If further changes are required, please leave a mesage.

**Pull request merged**
