### PR TITLE
add doc for serving http

### PR DESCRIPTION
**Pull request by glorysdj**
This change is [Reviewable](https://reviewable.io/reviews/intel-analytics/analytics-zoo/2386)

### CODE REVIEW

**Comment by Litchilitchy** [comment]
is it better to move http to Inference Chapter and combine with Python API, introducing 2 types of data pipeline IO together? @glorysdj @jason-dai

**Comment by glorysdj** [comment]
> is it better to move http to Inference Chapter and combine with Python API, introducing 2 types of data pipeline IO together? @glorysdj @jason-dai


> is it better to move http to Inference Chapter and combine with Python API, introducing 2 types of data pipeline IO together? @glorysdj @jason-dai

**Comment by glorysdj** [comment]
> is it better to move http to Inference Chapter and combine with Python API, introducing 2 types of data pipeline IO together? @glorysdj @jason-dai

I think http is relatively independent. user will not be confused if we put http separated with python programming inputs.

**Comment by glorysdj** [comment]
jenkins passed: http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/3512/

**Pull request merged**
