### PR TITLE
Set serializer to java in conf for TextClassification example

### PR DESCRIPTION
**Pull request by hkvision**
Since kryo serializer will cause problem

### CODE REVIEW

**Comment by jason-dai** [comment]
Can we do it by default in init_nncontext?

**Comment by hkvision** [comment]
@jason-dai You want to use java serializer everywhere? Then I think we can specify this in `spark-analytics-zoo.conf`?

**Comment by jason-dai** [comment]
Yes, maybe we should do that.

**Comment by hkvision** [comment]
Okay. I will create another PR to do this.

**Pull request closed without merging**
