### PR TITLE
Update run-app-tests.sh

### PR DESCRIPTION
**Pull request by yunyanliluo**

### CODE REVIEW

**Comment by hkvision** [comment]
What's the purpose of this PR?

**Comment by glorysdj** [comment]
this PR is to update the run-apps script to accept different arguments to run different parts of the apps to split the one long jenkins job to several parts

**Comment by hkvision** [comment]
Okay. Splitting into several jobs is a good choice, but doing it in this way is bit awkward...

**Comment by glorysdj** [comment]
by default, if no arguments is passed to it, it remains the old way, run all of the apps.

**Pull request closed without merging**
