### PR TITLE
Update UTs and examples with init_orca_context

### PR DESCRIPTION
**Pull request by hkvision**
- Update all UTs and examples in Orca.
- Update README.
- Fix some import ray issues.

### CODE REVIEW

**Comment by hkvision** [comment]
What about making default cluster_mode to "local"? As it would be more commonly used. @jason-dai

**Comment by jason-dai** [comment]
If we change default to "local", maybe we should use "spark" (or "spark_submit") instead of "" when user needs to manually  start the spark job?

**Comment by hkvision** [comment]
> If we change default to "local", maybe we should use "spark" (or "spark_submit") instead of "" when user needs to manually start the spark job?

Yeah, makes sense. I would change that.

**Comment by hkvision** [comment]
Tested the examples manually on yarn.

**Comment by hkvision** [comment]
jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation/4126/

**Pull request merged**
