### PR TITLE
image similarity notebook

### PR DESCRIPTION
**Pull request by hhbyyh**

### CODE REVIEW

**Comment by jason-dai** [comment]
cannot view the images?

**Comment by hhbyyh** [comment]
Updated.

**Comment by hhbyyh** [comment]
@jenniew can you please help review this? Thanks.
also cc @jason-dai for other comments.

**Comment by jason-dai** [comment]
LGTM

**Comment by hhbyyh** [comment]
Thanks for the review. http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/691/ passed. 
Merging to master. Closes hhbyyh/intel-analytics/zoo/#76

**Pull request merged**
