### PR TITLE
add ftp for app tests

### PR DESCRIPTION
**Pull request by Le-Zheng**

### CODE REVIEW

**Comment by glorysdj** [comment]
part2 passed 
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-AppTests-part2/14/console

**Comment by Le-Zheng** [comment]
part3 passed
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-AppTests-part3/21/

**Comment by glorysdj** [comment]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-AppTests-part3/21/console
passed

**Comment by Le-Zheng** [comment]
part1 passed
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-AppTests-part1/12/console

**Pull request merged**
