### PR TITLE
[ONNX] squeeze

### PR DESCRIPTION
**Pull request by cynthia-liu**

### CODE REVIEW

**Comment by cynthia-liu** [comment]
Check console output at http://10.239.47.211:18888/job/ZOO-PR-Validation/1418/ to view the results.

**Comment by zhichao-li** [comment]
add a unitest for axis=0?

**Comment by cynthia-liu** [comment]
http://10.239.47.211:18888/job/ZOO-PR-Validation/1430/

**Comment by cynthia-liu** [comment]
http://10.239.47.211:18888/view/ZOO-PR/job/ZOO-PR-Validation/1456/

**Comment by zhichao-li** [comment]
Where's the logic for checking outputshape?

**Comment by cynthia-liu** [comment]
ZOO-PR-Validation - Build # 1472 - Successful:

Check console output at http://10.239.47.211:18888/job/ZOO-PR-Validation/1472/ to view the results.

**Pull request merged**
