### PR TITLE
add release.rst in readthedocs

### PR DESCRIPTION
**Pull request by helenlly**
1) add release download page via release.rst
2) hidden the release page from index page, only show it in the left

### CODE REVIEW

**Comment by helenlly** [comment]
test website: https://testhelendoc.readthedocs.io/en/latest/

**Comment by hkvision** [comment]
https://testhelendoc.readthedocs.io/en/latest/release.html
Can we make the second column narrower? The layout is not good for now.

**Comment by hkvision** [comment]
Why do you hide the release from the index?

**Comment by helenlly** [comment]
> Why do you hide the release from the index?

re-design to show it in both index and left menu

**Comment by helenlly** [comment]
> https://testhelendoc.readthedocs.io/en/latest/release.html
> Can we make the second column narrower? The layout is not good for now.

done

**Comment by jason-dai** [comment]
why both rst and md files?

**Comment by helenlly** [comment]
> why both rst and md 
deleted rst file

**Comment by hkvision** [comment]
https://testhelendoc.readthedocs.io/en/latest/doc/release.html
The table layout is broken now...

**Comment by jason-dai** [comment]
> https://testhelendoc.readthedocs.io/en/latest/doc/release.html
> The table layout is broken now...

The list is too long; we can also delete the old ones.

**Comment by helenlly** [comment]
will update the link and open a new PR

**Pull request closed without merging**
