### PR TITLE
Cluster Serving simplified auto Benchmark

### PR DESCRIPTION
**Pull request by Litchilitchy**
with one dist directory, can use this script to get result

no init -> start -> push .... manually anymore

### CODE REVIEW

**Comment by jason-dai** [comment]
maybe this should go to test folder

**Comment by Litchilitchy** [comment]
> maybe this should go to test folder

test folder will not be packaged in dist folder?

**Comment by jason-dai** [comment]
Why do we want to release them? They are used for testing and development, no?

**Comment by Litchilitchy** [comment]
> Why do we want to release them? They are used for testing and development, no?

Will move to test folder and give new api.

**Comment by Litchilitchy** [comment]
fixed

**Pull request merged**
