### PR TITLE
Add get_uri to Python Imageset API.

### PR DESCRIPTION
**Pull request by hhbyyh**
Enable users to map the image, label, predict to URI, this will further allow setting labels to Images.

### CODE REVIEW

**Comment by jason-dai** [comment]
Why Python only?

**Comment by hhbyyh** [comment]
Scala API already exposed access for ImageFeature, user can get URI using map operation.

**Comment by jason-dai** [comment]
We should scala and python APIs consistent as much as possible

**Comment by jason-dai** [comment]
I don't think we need to expose Imagefeature at this moment. We should add new helper methods (like get_uri) to both Scala and Python APIs though.

**Comment by dding3** [comment]
Synced with yuhao offline, it would be convenient if we can have a "get" method for both scala and python, which supports user get the value of imageset with provided field. Since localImageSet returns a array while distributedImageSet returns a rdd, we may need add "getList" and "getRdd" separately for localImageSet and distributedImageset.

**Pull request closed without merging**
