### PR TITLE
migrate bigdl to bigdl2.0

### PR DESCRIPTION
**Pull request by dding3**

### CODE REVIEW

**Comment by dding3** [comment]
example test status:
examples_test_status

**Comment by dding3** [comment]
ut test status:
1. http://10.112.231.51:18080/view/BigDL-2.0/job/BigDL2.0-PR-scalatest-optim-spark2.4/ **pass**
2. http://10.112.231.51:18080/view/BigDL-2.0/job/BigDL2.0-PR-scalatest-mkldnn-spark2.4/ **Pass**
3. http://10.112.231.51:18080/view/BigDL-2.0/job/BigDL2.0-PR-scalatest-others-spark2.4/ **7 test cases failed**
    The failed test cases are:
    BlasToDnnSpec.scala
    1. "inception_v1 blas to dnn" should "work properly"
    2. resnet50 blas to dnn 
    3. resnet50 dnn to blas

    DnnPredictorSpec.scala
    1. "predict image for dnn", 
    2. "Evaluator with dnn backend" should "be correct"
    3. "Evaluator MiniBatch with dnn backend"

    TruncatedNormalSerialTest

   The first 6 test cases pass on my local env. @Le-Zheng Could you please check jekins configurations.
   The last one failed on my local env. Tried to run the ut on original bigdl branch, also failed.

**Comment by dding3** [comment]
@jason-dai Shall we move on to migrate python dllib or fix the failed examples and unit tests?

**Comment by jason-dai** [comment]
> @jason-dai Shall we move on to migrate python dllib or fix the failed examples and unit tests?

Let's merge the scala dllib first.

**Comment by dding3** [comment]
@Le-Zheng Thank you for the update which is quite reassurance. Created a test issue to follow up https://github.com/intel-analytics/analytics-zoo/issues/4471 

Seems all ut passed and have not find error in the example caused by the migration. Merge the PR first.

**Pull request merged**
