### PR TITLE
update ZOO_HOME to ANALYTICS_ZOO_HOME

### PR DESCRIPTION
**Pull request by dding3**
Fix https://github.com/intel-analytics/zoo/issues/199

### CODE REVIEW

**Comment by hhbyyh** [comment]
cc @jason-dai @hkvision .

Setting ANALYTICS_ZOO_HOME could be confusing for users, shall we rename `ANALYTICS_ZOO_HOME` to `ZOO_DIST`

**Comment by dding3** [comment]
For python example, we need a root folder to locate the python script(eg. predict.py). Setting `ANALYTICS_ZOO_HOME` for root folder and `ANALYTICS_ZOO_DIST` to dist folder?

**Comment by hhbyyh** [comment]
@dding3, can we replace `${ZOO_HOME}/pyzoo/zoo/examples/objectdetection/predict.py` with `path/to/predict.py`, `predict.py` should be able to run anywhere as long as `ANALYTICS_ZOO_DIST` is set correctly. We need to support the case that user has the pre-built binaries only and wants to try with the predict.py.

Agree with @hkvision 's suggestion
> ANALYTICS_ZOO_ROOT=root dir
> Primarily use ANALYTICS_ZOO_HOME if possible.

The usage of `ANALYTICS_ZOO_ROOT` should be restricted to build and test script only.

**Comment by hkvision** [comment]
Yeah, we should use `ANALYTICS_ZOO_HOME=dist dir` whenever possible.
In the TextClassification README, I use `ANALYTICS_ZOO_ROOT` and `${ANALYTICS_ZOO_ROOT}/pyzoo/zoo/examples/textclassification/text_classification.py` to refer to the file.

Emmm, feel free to update this if necessary to keep the README of examples consistent.

**Comment by hkvision** [comment]
cc @jason-dai

**Comment by jason-dai** [comment]
`ANALYTICS_ZOO_HOME=dist dir`
`ANALYTICS_ZOO_ROOT=src code root`

**Comment by hhbyyh** [comment]
LGTM

**Comment by dding3** [comment]
Thanks for your review and suggestions.

Jekins pass. http://172.168.2.101:8080/job/ZOO-PR-Validation/476/

**Pull request merged**
