### PR TITLE
Add Orca metrics and utils unit tests

### PR DESCRIPTION
**Pull request by leonardozcm**
Add pytest [test_metrics.py](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/test/zoo/orca/learn/test_metrics.py) and [test_utils.py](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/test/zoo/orca/learn/test_utils.py)

### CODE REVIEW

**Comment by hkvision** [comment]
Also remove the duplicate header in test_utils.py

**Comment by leonardozcm** [comment]
> Also remove the duplicate header in test_utils.py



> duplicate header

fixed

**Comment by yangw1234** [comment]
Is this pr ready to merge?

**Comment by leonardozcm** [comment]
> Is this pr ready to merge?

Not for now, since there comes out some issues on metric UT.

**Comment by leonardozcm** [comment]
http://10.239.47.210:18888/job/ZOO-PR-Validation/5269/

**Comment by hkvision** [comment]
http://10.239.47.210:18888/job/ZOO-PR-Python-Spark-2.4-py36/3685/console

**Comment by hkvision** [comment]
LGTM. Need to rebase with master

**Comment by yangw1234** [comment]
LGTM let's merge it after jenkins passed

**Comment by leonardozcm** [comment]
http://10.239.47.210:18888/job/ZOO-PR-Validation/5284/

**Pull request merged**
