### PR TITLE
session_recommender integration-test

### PR DESCRIPTION
**Pull request by aqtjin**

### CODE REVIEW

**Comment by hkvision** [comment]
Can merge it after jenkins passed.

**Comment by qiyuangong** [comment]
@aqtjin  Pls add passed jenkins url with comment. :)

**Comment by aqtjin** [comment]
http://10.239.47.211:18888/view/ZOO-NB/job/ZOO-NB-Integration-Test/629/console

**Comment by aqtjin** [comment]
@songhappy

**Comment by hkvision** [comment]
Merged. Thank you for your efforts!

**Pull request merged**
