### PR TITLE
Move time series part from automl to zouwu

### PR DESCRIPTION
**Pull request by yushan111**
This PR mainly changes below code paths.

- `automl/features` -> `zouwu/features`
- `automl/model` -> `zouwu/model/forecast/model`
- `automl/config` -> `zouwu/config`
- move and merge `automl/impute` with `zouwu/preprocessing/impute` (needed refactoring to remove similar code)
- `automl/pipeline/time_sequence.py` -> `zouwu/pipeline`
- `automl/regression/time_sequence_predictor.py` & `automl/regression/xgb_predictor.py` -> `zouwu/regression`

### CODE REVIEW

**Comment by yushan111** [comment]
Tasks:

- [ ] code 
- [ ] UT
- [ ] notebook
- [ ] examples

**Comment by yushan111** [comment]
Jenkins passed:
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/5242/
http://10.239.47.210:18888/job/ZOO-PR-Python-Spark-2.4-py37/2084/

**Comment by yushan111** [comment]
app test passed: 
http://10.239.47.210:18888/job/ZOO-NB-Pip-AppTests-part4/363/

**Comment by jason-dai** [comment]
A few comments:
1) For AotuML:
    - We should keep the base `Recipe` class in `automl\recipe` folder
    - We should keep `BaseModel`, `PytorchBaseModel` and `KerasBaseModel` in `automl\model` folder
    - We should move `XGBoost` to `orca\automl\AutoXGBoost`
    - We may move the `automl` module to `orca\automl` @shane-huang @yushan111 ?
2) For Zouwu
    - We should move `automl\model\*` to `zouwu\model\*`
    - Under `automl\model`, you may have two submodules: `zouwu\model\forecast` and `zouwu\model\anomaly`

**Comment by yushan111** [comment]
>    * We may move the `zoo\automl` module to `zoo\orca\automl` @shane-huang @yushan111 ?

We plan to work on the new interface of `AutoEstimator` in `zoo\orca\automl` since it is a clean directory and move the `zoo\automl` module part by part.

**Comment by yushan111** [comment]
> 2. For Zouwu:
>    * We should move `automl\model\*` to `zouwu\model\*`

Since the old contents in `automl\model` has been moved to `zouwu/model/forecast/model` and the models might be only used for forecast but not anomaly, maybe I could change name from `model` to `impl` in `zouwu/model/forecast/` to avoid confusion. 
Is that ok?

**Comment by yushan111** [comment]
> 2. For Zouwu:
>    
>    * Under `automl\model`, you may have two submodules: `zouwu\model\forecast` and `zouwu\model\anomaly`
I will move `anomly.py` under `zouwu\model\anomaly`

**Pull request merged**
