### PR TITLE
Support init_spark_on_k8s

### PR DESCRIPTION
**Pull request by hkvision**
- Add init_spark_on_k8s
- Code refactor for yarn, standalone and k8s

### CODE REVIEW

**Comment by hkvision** [comment]
@jason-dai @glorysdj Currently hyperzoo image for k8s downloads Spark and Analytics Zoo for spark-submit.
But init_spark_on_k8s is supposed to use pip install analytics-zoo and pyspark. I think both can be included in one image. Any good ideas?

**Comment by hkvision** [comment]
This is an initial PR tested on tfpark keras_dataset example on k8s cluster.

**Comment by hkvision** [comment]
@glorysdj Take a look at the updated Dockerfile? I tested it can both work with spark-submit or init_spark_on_k8s.

**Review by glorysdj — APPROVED** [review]
Dockerfile LGTM

**Comment by hkvision** [comment]
Manually tested the modifications on yarn and standalone.

**Comment by hkvision** [comment]
jenkins http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/4150/

**Pull request merged**
