### PR TITLE
Fix a small issue at tf_ray_estimator

### PR DESCRIPTION
**Pull request by leonardozcm**
when debuging lstm in orca,  initializing tf2 estimator may raise error:

```
Traceback (most recent call last):
  File "/home/arda/PycharmProjects/forecasting_with_lstm/lstm_orca", line 154, in <module>
    train()
  File "/home/arda/PycharmProjects/forecasting_with_lstm/lstm_orca", line 105, in train
    est = Estimator.from_keras(model_creator=model_creator)
  File "/home/arda/Project/analytics-zoo/pyzoo/zoo/orca/learn/tf2/tf_ray_estimator.py", line 191, in from_keras
    backend=backend, compile_args_creator=compile_args_creator)
  File "/home/arda/Project/analytics-zoo/pyzoo/zoo/orca/learn/tf2/tf_ray_estimator.py", line 131, in __init__
    if "intra_op_parallelism" not in config:
TypeError: argument of type 'NoneType' is not iterable
```

Add class attribute `self.` to `config` fix this bug.

### CODE REVIEW

**Comment by yangw1234** [comment]
LGTM, have you run the pr validation job?

**Comment by leonardozcm** [comment]
> LGTM, have you run the pr validation job?

sure, I will do the jenkins validation

**Comment by leonardozcm** [comment]
Two PR-Validation ended with different tasks failed, maybe it is caused by an random error.
http://10.239.47.210:18888/job/ZOO-PR-Validation/4762/
http://10.239.47.210:18888/job/ZOO-PR-Validation/4763/

**Comment by leonardozcm** [comment]
> Two PR-Validation ended with different tasks failed, maybe it is caused by an random error.
> http://10.239.47.210:18888/job/ZOO-PR-Validation/4762/
> http://10.239.47.210:18888/job/ZOO-PR-Validation/4763/

**Pull request merged**
