### PR TITLE
Add Zouwu Stock Prediction Example using LSTMForecaster

### PR DESCRIPTION
**Pull request by PeterQiu0516**
Add Zouwu Stock Prediction Example using LSTMForecaster.

### CODE REVIEW

**Comment by shane-huang** [comment]
1. 
>In this notebook, we demonstrate a reference use case where we use hitorical stock price data to predict the future price. The dataset we use is the daily stock price of S&P500 stocks during 2013-2018 ([data source](https://www.kaggle.com/camnugent/sandp500/)). We demostrate how to do univariate forecasting using the past 966 days of MMM price to predict the future 244 days of the price. 
Reference: https://github.com/jwkanggist/tf-keras-stock-pred

**Comment by shane-huang** [comment]
Add a short README.md as the other use case does.

**Comment by PeterQiu0516** [comment]
> 1. the introduction needs a reference to the data source, and also the notebook reference. Possbily change to below.
> 
> > In this notebook, we demonstrate a reference use case where we use hitorical stock price data to predict the future price. The dataset we use is the daily stock price of S&P500 stocks during 2013-2018 ([data source](https://www.kaggle.com/camnugent/sandp500/)). We demostrate how to do univariate forecasting using the past 966 days of MMM price to predict the future 244 daily price.
> > Reference: https://github.com/jwkanggist/tf-keras-stock-pred
> 
> 1. change the title "Download raw dataset and load into dataframe"  to "Get Data".
> 2. add a new text cell under "Get Data" and contents as below.
> 
> ```
> We will use the close prices of MMM stock for our experiment. We will 
>   1. download raw dataset and load into dataframe. 
>   2. Extract the close prices of MMM stock from the dataframe into a numpy array
> ```
> 
> 1. In cell2: Remove the google and Yahoo dataset below as we don't use them
> 
> ```python
> # YAHOO
> # FILE_NAME    = 'prices.csv'
> #SOURCE_URL = 'https://www.kaggle.com/dgawlik/nyse/downloads/prices.csv/' 
> 
> # GOOGLE
> # FILE_NAME    = 'trainset.csv'
> # SOURCE_URL = 'https://www.kaggle.com/ptheru/googledta/downloads/trainset.csv/' 
> ```
> 
> 1. after cell 4, plot a curve of all MMM stock price to give people a global view of how MMM price looks like.
> 2. Remove the title "Data Preparation"
> 3. In cell 10, remove "num_direction = 1 # 1 for LSTM, 2 for Bi-LSTM". this hp is not used.
> 4. In the last plot, use blue color for actual values and red color for predicted values, because it is the common practice in all our notebooks. You can also add a legend to specify which color is atucal values as network traffic notebook does.

Resolved.

**Comment by PeterQiu0516** [comment]
> Add a short README.md as the other use case does.

Resolved.

**Comment by shane-huang** [comment]
1. change 
> We will use the close prices of MMM stock for our experiment. We will
to 
> We use the close prices of MMM stock for our experiment. Steps are

2. in cell 6, change the label "S&P 500 Raw" to "MMM daily price Raw"
3. add the notebook to tests scripts.

**Comment by shane-huang** [comment]
Change the notebook title to "Stock Price Prediction"

**Comment by PeterQiu0516** [comment]
> 1. change
> 
> > We will use the close prices of MMM stock for our experiment. We will
> > to
> > We use the close prices of MMM stock for our experiment. Steps are
> 
> 1. in cell 6, change the label "S&P 500 Raw" to "MMM daily price Raw"
> 2. change the notebook title to "Stock Price Prediction"
> 3. add the notebook to tests scripts.

Fixed.

**Comment by PeterQiu0516** [comment]
Jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation/5500/

**Pull request merged**
