### PR TITLE
update the key dependencies version 

### PR DESCRIPTION
**Pull request by pinggao187**

### CODE REVIEW

**Comment by Le-Zheng** [comment]
also need to update spark version in https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/setup.py#L141

**Comment by pinggao187** [comment]
test
http://10.239.176.111:18888/view/ZOO-PR/job/ZOO-PR-Validation/6003/
http://10.239.176.111:18888/view/ZOO-PR/job/ZOO-PR-Scala-Spark-2.4-pom/1/console

**Comment by hkvision** [comment]
Also need to update relase_default.sh? And the document in the shell scripts?

**Comment by pinggao187** [comment]
test
http://10.239.176.111:18888/view/ZOO-PR/job/ZOO-PR-Validation/6016/
http://10.239.176.111:18888/job/ZOO-PR-Python-ExampleTests-py37-Spark3/1510/

**Pull request merged**
