### PR TITLE
Upgrade ray to 0.8.4

### PR DESCRIPTION
**Pull request by yangw1234**
- [x] unit test environment
- [x] automl change
- [x] verify docker (docker will be updated later)
- [ ] pr validation

### CODE REVIEW

**Comment by yangw1234** [comment]
Hi @hkvision @shane-huang @jenniew @yushan111 , is it ok for you guys if I upgrade ray version to 0.8.4?

**Comment by hkvision** [comment]
I‘m ok with 0.8.4.
Also need to update all documents.

**Comment by yushan111** [comment]
I need to change some code of ray tune. Maybe need some time and will upgrade later. I will update here as soon as ray 0.8.4 is supported.

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/job/ZOO-PR-Python-Spark-2.4-py36/1676/console py36 passed on Ritchie

**Comment by shane-huang** [comment]
add reference to automl issue about upgrading #2282

**Comment by yangw1234** [comment]
example tests passed http://172.168.2.101:8080/job/ZOO-PR-Python-ExampleTests/470/

**Comment by yangw1234** [comment]
other ut passed http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/3269/ spark2.3 failure is irrelevant

**Comment by yangw1234** [comment]
I'll first merge it as jenkins job has already upgraded to ray 0.8.4. If additional changes are needed, I'll address them in future pr.

**Comment by shane-huang** [comment]
fixed issue #2282

**Pull request merged**
