### PR TITLE
rename notebook to apps

### PR DESCRIPTION
**Pull request by dding3**
What changes were proposed in this pull request?
Rename notebook to apps

How was this patch tested?
Not needed

Related links or issues (optional)
https://github.com/intel-analytics/zoo/issues/202

### CODE REVIEW

**Comment by dding3** [comment]
Jekins passed.
Link: # 262

**Comment by jenniew** [comment]
For some .keep files, you can remove them.

**Comment by jenniew** [comment]
LGTM

**Comment by dding3** [comment]
Jekins passed. Link: # 282

**Pull request merged**
