### PR TITLE
add execute permission to scripts

### PR DESCRIPTION
**Pull request by hhbyyh**
Right now I'm getting permission denied when trying to run the examples.

### CODE REVIEW

**Comment by hhbyyh** [comment]
cc @yangw1234

**Comment by yangw1234** [comment]
LGTM

**Comment by hhbyyh** [comment]
http://172.168.2.101:8080/view/ZOO-PR-PIPELINE/job/ZOO-PR-Validation/2660/ passed

**Comment by hkvision** [comment]
Need to backport to branch 0.6 @hhbyyh

**Pull request merged**
