### PR TITLE
Doc: fix error link(chronos-autotsest-quickstart.md)

### PR DESCRIPTION
**Pull request by liangs6212**

### CODE REVIEW

**Comment by TheaperDeng** [comment]
may be we can util this PR as a quickstart recheck before our mid oct release.

**Comment by liangs6212** [comment]
https://liang.readthedocs.io/en/fix_readthedocs/doc/Chronos/QuickStart/chronos-autotsest-quickstart.html?highlight=visual

**Review by TheaperDeng — APPROVED** [review]
run jenkins

**Comment by liangs6212** [comment]
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-2.3-py37/3282/
http://10.112.231.51:18888/job/ZOO-PR-Python-ExampleTests-py37/3409/
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-3.1-py36k216/1887/
http://10.112.231.51:18888/job/ZOO-PR-Validation/6441/

**Pull request merged**
