### PR TITLE
Spark 3.1.2 

### PR DESCRIPTION
**Pull request by Le-Zheng**
0.14.0-SNAPSHOT

### CODE REVIEW

**Comment by glorysdj** [comment]
https://github.com/intel-analytics/analytics-zoo/blob/0d1edebc5017c015a2923b6efed4cd92222fd711/zoo/pom.xml#L166
is this version also needed to be changed?

**Comment by Le-Zheng** [comment]
> https://github.com/intel-analytics/analytics-zoo/blob/0d1edebc5017c015a2923b6efed4cd92222fd711/zoo/pom.xml#L166
> 
> 
> is this version also needed to be changed?

Done 
<spark-version.project>3.1</spark-version.project>
<spark.version>3.1.2</spark.version>

**Comment by Le-Zheng** [comment]
passed 
http://10.112.231.51:18888/job/ZOO-PR-Validation-Spark-3.0/1600/ 
http://10.112.231.51:18888/job/ZOO-PR-Python-ExampleTests-py37-Spark3/1693/ + http://10.112.231.51:18888/job/ZOO-PR-Python-ExampleTests-py37-ray-Spark3/1681/ + http://10.112.231.51:18888/job/ZOO-PR-Python-ExampleTests-py37-ray-horovod-Spark3/1598/

**Comment by Le-Zheng** [comment]
jenkins: http://10.112.231.51:18888/job/ZOO-PR-Validation/6181/

**Pull request merged**
