### PR TITLE
[Automl] Change default look back value and evaluation output format while future_seq_len=1

### PR DESCRIPTION
**Pull request by yushan111**
main changes:
1. add result analysis in ray 0.7.4 (searcher.run() returns ExperimentAnalysis instead of trials)
2. change default look back length from 1 to 2. Add input check and some corresponding UTs
3. while future_seq_len=1, output one value instead of an array

### CODE REVIEW

**Comment by shane-huang** [comment]
Does it break if we use ray 0.7.2?  ray 0.7.4 has some issues I think.

**Comment by jason-dai** [comment]
I think we should use Ray 0.6.6 (https://analytics-zoo.github.io/master/#ProgrammingGuide/rayonspark/) according to @zhichao-li ?

**Comment by zhichao-li** [comment]
Previously, we test against 0.6.6 and it works smoothly, but the latest version would have some known issue. Take a look at these issues: https://github.com/ray-project/ray/issues/5223 and #5454

**Comment by richardliaw** [comment]
@yushan111 @shane-huang @jason-dai @zhichao-li 

I'm from the ray team and maintain tune - have you all joined the ray slack? let's setup a channel to chat!

**Comment by yushan111** [comment]
> main changes:
> 
> 1. add result analysis in ray 0.7.4 (searcher.run() returns ExperimentAnalysis instead of trials)
> 2. change default look back length from 1 to 2. Add input check and some corresponding UTs
> 3. while future_seq_len=1, output one value instead of an array

Code related to ray 0.7.4 is removed. 
I think it works well with ray version<= 0.7.0 .

**Pull request merged**
