### PR TITLE
Download MXNet MNIST data from FTP in integration

### PR DESCRIPTION
**Pull request by hkvision**

### CODE REVIEW

**Comment by glorysdj** [comment]
also need to upload $FTP_URI/analytics-zoo-data/mnist.zip to http

**Comment by hkvision** [comment]
Succeeded: http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests-py36-ray/31/console
```
2020-07-20 12:51:56 URL: ftp://zoo:*password*@10.239.47.210/analytics-zoo-data/mnist.zip [11595270] -> "/opt/work/jenkins/workspace/ZOO-PR-Python-ExampleTests-py36-ray/data/mnist.zip" [1]

[2m[36m(pid=37978)[0m INFO:filelock:Lock 140205914266592 acquired on data.lock
[2m[36m(pid=37978)[0m [12:52:23] src/io/iter_mnist.cc:113: MNISTIter: load 30000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=37978)[0m [12:52:24] src/io/iter_mnist.cc:113: MNISTIter: load 5000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=37978)[0m INFO:filelock:Lock 140205914266592 released on data.lock
[2m[36m(pid=37978)[0m INFO:filelock:Lock 140205914266592 acquired on data.lock
[2m[36m(pid=37978)[0m [12:52:24] src/io/iter_mnist.cc:113: MNISTIter: load 30000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=37980)[0m INFO:filelock:Lock 140048523926496 acquired on data.lock
[2m[36m(pid=37978)[0m [12:52:24] src/io/iter_mnist.cc:113: MNISTIter: load 5000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=37978)[0m INFO:filelock:Lock 140205914266592 released on data.lock
[2m[36m(pid=37980)[0m [12:52:25] src/io/iter_mnist.cc:113: MNISTIter: load 30000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=37980)[0m [12:52:25] src/io/iter_mnist.cc:113: MNISTIter: load 5000 images, shuffle=1, shape=[256,1,28,28]
```
Not downloading any more.

**Comment by hkvision** [comment]
Previously, http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests-py36-ray/17/console
```
[2m[36m(pid=110557)[0m INFO:filelock:Lock 139717059750768 acquired on data.lock
[2m[36m(pid=110557)[0m INFO:root:downloaded http://data.mxnet.io/mxnet/data/mnist.zip into data/mnist.zip successfully
[2m[36m(pid=110557)[0m [03:30:48] src/io/iter_mnist.cc:113: MNISTIter: load 30000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=110557)[0m [03:30:48] src/io/iter_mnist.cc:113: MNISTIter: load 5000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=110557)[0m INFO:filelock:Lock 139717059750768 released on data.lock
[2m[36m(pid=110557)[0m INFO:filelock:Lock 139717059750768 acquired on data.lock
[2m[36m(pid=110557)[0m [03:30:49] src/io/iter_mnist.cc:113: MNISTIter: load 30000 images, shuffle=1, shape=[256,1,28,28]
[2m[36m(pid=110557)[0m [03:30:49] src/io/iter_mnist.cc:113: MNISTIter: load 5000 images, shuffle=1, shape=[256,1,28,28]
```

**Comment by hkvision** [comment]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/3818/ One job failure is due to network.
Thanks so much for your review @qiyuangong

**Pull request merged**
