### PR TITLE
Fix build failure

### PR DESCRIPTION
**Pull request by dding3**
1. Fix https://github.com/intel-analytics/analytics-zoo/issues/2954
2. Fix https://github.com/intel-analytics/analytics-zoo/issues/2941

### CODE REVIEW

**Review by qiyuangong — APPROVED** [review]
LGTM

**Comment by qiyuangong** [comment]
Do we need to skip Scala Unit test?

**Comment by dding3** [comment]
> Do we need to skip Scala Unit test?

Have added the logic to skip ut if the os is not linux.

**Comment by dding3** [comment]
Python mac ut passed:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.1-PYTHON-MAC/124/

app test jekins passed.
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Pip-AppTests-part4/189/

pr validation jekins failed. but the failure is env issue, not related to the pr.
http://10.239.47.210:18888/job/ZOO-PR-Python-Spark-2.4-py36/2767/console

**Pull request merged**
