### PR TITLE
upgrade ray to 1.0

### PR DESCRIPTION
**Pull request by yangw1234**

### CODE REVIEW

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/job/ZOO-PR-Python-Spark-3.0-py37-ray/551/console ray unit passed

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/job/ZOO-PR-Python-Spark-3.0-py37-Horovod/551/ horovod unit tests passed

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/job/ZOO-PR-Python-ExampleTests-py37-ray-horovod-Spark3/440/ horovod example tests passed

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/job/ZOO-PR-Python-Spark-3.0-py37-ray/572/ ray unit tests

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/job/ZOO-PR-Python-ExampleTests-py37-ray-horovod-Spark3/452/ horovod unit test

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/job/ZOO-PR-Python-ExampleTests-py37-ray-horovod-Spark3/452/ horovod example

**Comment by jason-dai** [comment]
Need to update the document at https://github.com/intel-analytics/analytics-zoo/blob/master/readthedocs/source/doc/UserGuide/ray.md and https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ProgrammingGuide/rayonspark.md

**Comment by yangw1234** [comment]
> Need to update the document at https://github.com/intel-analytics/analytics-zoo/blob/master/readthedocs/source/doc/UserGuide/ray.md and https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ProgrammingGuide/rayonspark.md

updated #3568

**Pull request merged**
