### PR TITLE
[Horovod] Support multiple workers in one spark executor

### LINKED ISSUE #2703: Horovod for Spark local can only start one worker
Better make num_workers configurable. Otherwise running in local doesn't make any sense.

### PR DESCRIPTION
**Pull request by yangw1234**
Fix #2703

### CODE REVIEW

**Comment by hkvision** [comment]
What about just specifying num_workers and worker_cores / worker_cpus? Sometimes users don't necessarily need to use all the yarn cluster resources?

**Comment by yangw1234** [comment]
> What about just specifying num_workers and worker_cores / worker_cpus? Sometimes users don't necessarily need to use all the yarn cluster resources?
If we do not use all the yarn cluster resources, some workers may not have tasks at all. Does it work with xshards in this case?

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/4052/ jenkins passed

also tested manually on resnet50

**Comment by yangw1234** [comment]
@hkvision  I'll first merge it. Let's discuss the num_workers issues later.

**Comment by hkvision** [comment]
LGTM. For XShards, I think it requires there are workers on each node. But if users don't use XShards, it is still possible to have fewer workers?

**Pull request merged**
