### PR TITLE
Releasefix

### PR DESCRIPTION
**Pull request by glorysdj**
this pr is to fix msssing apps in dist.zip

the structure of the dist-all.zip will be
tree analytics-zoo-0.2.0-SNAPSHOT-spark-2.1.0-dist-all
analytics-zoo-0.2.0-SNAPSHOT-spark-2.1.0-dist-all
├── apps
│   ├── anomaly-detection
│   │   ├── anomaly-detection-nyc-taxi.ipynb
│   │   └── README.md
│   ├── dogs-vs-cats
│   │   ├── README.md
│   │   └── transfer-learning.ipynb
│   ├── fraud-detection
│   │   ├── fraud-1.0.1-SNAPSHOT.jar
│   │   ├── fraud-detection.ipynb
│   │   ├── README.md
│   │   └── run.sh
│   ├── image-augmentation
│   │   ├── image
│   │   │   └── test.jpg
│   │   ├── image-augmentation.ipynb
│   │   └── README.md
│   ├── ipynb2py.sh
│   ├── object-detection
│   │   ├── download_model.sh
│   │   ├── object-detection.ipynb
│   │   └── README.md
│   ├── recommendation
│   │   ├── ncf-explicit-feedback.ipynb
│   │   ├── README.md
│   │   └── wide_n_deep.ipynb
│   ├── run-app-tests.sh
│   ├── sentiment-analysis
│   │   ├── README.md
│   │   └── sentiment.ipynb
│   ├── tfnet
│   │   ├── image_classification_inference.ipynb
│   │   ├── imagenet_class_index.json
│   │   ├── README.md
│   │   └── test.jpg
│   ├── variational-autoencoder
│   │   ├── README.md
│   │   ├── standard_autoencoder.jpg
│   │   ├── using_variational_autoencoder_and_deep_feature_loss_to_generate_faces.ipynb
│   │   ├── using_variational_autoencoder_to_generate_digital_numbers.ipynb
│   │   ├── using_variational_autoencoder_to_generate_faces.ipynb
│   │   ├── utils.py
│   │   └── vae.jpg
│   └── variational-autoencoder-keras
│       ├── standard_autoencoder.jpg
│       ├── using_variational_autoencoder_and_deep_feature_loss_to_generate_faces.ipynb
│       ├── using_variational_autoencoder_to_generate_digital_numbers.ipynb
│       ├── using_variational_autoencoder_to_generate_faces.ipynb
│       ├── utils.py
│       └── vae.jpg
├── bin
│   ├── data
│   │   ├── glove
│   │   │   └── get_glove.sh
│   │   ├── movielens-1m
│   │   │   └── get_movielens-1m.sh
│   │   ├── NAB
│   │   │   └── nyc_taxi
│   │   │       └── get_nyc_taxi.sh
│   │   └── news20
│   │       └── get_news20.sh
│   ├── jupyter-with-zoo.sh
│   ├── pyspark-with-zoo.sh
│   ├── python_package.sh
│   ├── README.md
│   ├── requirements.txt
│   ├── spark-shell-with-zoo.sh
│   ├── spark-submit-with-zoo.sh
│   └── zoo-build-info
├── conf
│   └── spark-analytics-zoo.conf
├── extra-resources
│   └── zoo-version-info.properties
└── lib
    ├── analytics-zoo-0.2.0-SNAPSHOT-jar-with-dependencies.jar
    └── analytics-zoo-0.2.0-SNAPSHOT-python-api.zip

---
This change is [Reviewable](https://reviewable.io/reviews/intel-analytics/analytics-zoo/412)

### CODE REVIEW

**Comment by hkvision** [comment]
After this PR, make-dist will generate the folder `dist-all` instead of `dist` right?

**Comment by jason-dai** [comment]
We should keep both dist and dist-all?

**Comment by glorysdj** [comment]
1st, we will have both dist and dist-all for 0.1.0 (dist can not be deleted in the maven central), but we will change the doc to download zip with dist-all.zip. but in the future, only the dist-all with apps will be released.

2nd, after this pr, we will use dist-all instead of dist since the users may be getting used to dist-all. we may also change the name back to dist.zip in the 0.2.0.

is that ok? @jason-dai @hkvision

**Comment by jason-dai** [comment]
It might be a good idea to keep both dist and dist-all? E.g., apps can become bigger if we have many large notebooks; and one cannot easily find apps in pip @hkvision ?

**Comment by glorysdj** [comment]
ok, I will add both zip assembly files.

**Comment by jason-dai** [comment]
yes

**Comment by hkvision** [comment]
Thanks @jason-dai If necessary, I can add apps as well in the next release. :)

**Comment by glorysdj** [comment]
now, i have added both dist, dist-all, please review.
if there is no problem, please approve, and i will try to upload dist-all.zip to ossrh

**Pull request merged**
