### PR TITLE
support model with single output for NNClassifier.

### PR DESCRIPTION
**Pull request by hhbyyh**
Allow  NNClassifier to support model with a single scalar output, like a model with single sigmoid output.

### CODE REVIEW

**Comment by hhbyyh** [comment]
cc @dding3 can you help review this. Thanks.

**Comment by dding3** [comment]
LGTM. Please update the related doc.

**Comment by hhbyyh** [comment]
Thanks for the review. I'll further test the new function and finish doc in this release.

**Comment by hhbyyh** [comment]
PR validation 845 passed.

**Pull request merged**
