### PR TITLE
Fix plot_result function in zouwu network_traffic_autots_forecasting

### PR DESCRIPTION
**Pull request by liangs6212**

### CODE REVIEW

**Review by TheaperDeng — COMMENTED** [review]
Seem that some of the blocks are deleted (e.g. In[15], In[16] etc. in original notebook), please add back.

**Comment by liangs6212** [comment]
ln[15],ln[16] ,add complete

**Review by TheaperDeng — APPROVED** [review]
LGTM

**Comment by yushan111** [comment]
remove notes (in code on your branch), such as "调用了fitt" and "调用了tss_fit"

**Comment by yangw1234** [comment]
One minor comments: maybe it would better if the title is more explicit about what issue is being fixed?

**Comment by yushan111** [comment]
> One minor comments: maybe it would better if the title is more explicit about what issue is being fixed?

Thanks for your suggestion.

**Review by TheaperDeng — COMMENTED** [review]
Seems that the notebook is broken due to the improper handle of the conflict.

**Comment by liangs6212** [comment]
git branch and commit too confusion,resubmit

**Pull request closed without merging**
