### PR TITLE
Chronos: add YEAR feature in tsdata.gen_dt_feature.

### PR DESCRIPTION
**Pull request by liangs6212**
add year for tsdata.gen_dt_feature

### CODE REVIEW

**Comment by liangs6212** [comment]
#4100

**Review by TheaperDeng — APPROVED** [review]
pls run jenkins

**Comment by liangs6212** [comment]
http://10.112.231.51:18888/job/ZOO-PR-Validation/6394/
http://10.112.231.51:18888/job/ZOO-PR-Python-Spark-2.4-py36-ray/2650/
http://10.112.231.51:18888/job/ZOO-PR-Python-ExampleTests/3704/

**Comment by TheaperDeng** [comment]
pls rerun autotsest notebook and find out if "YEAR" can significantly affect the final result.

**Comment by liangs6212** [comment]
smape: ~6.5

**Pull request merged**
