### PR TITLE
Orca Ray example

### PR DESCRIPTION
**Pull request by leonardozcm**
Ported from https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/ray

### CODE REVIEW

**Comment by jason-dai** [comment]
Move to https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/ray_on_spark, and remove https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/ray

**Comment by leonardozcm** [comment]
> Move to https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/ray_on_spark, and remove https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/ray

sure

**Comment by leonardozcm** [comment]
Jenkins passed @yangw1234 
http://10.239.47.210:18888/job/ZOO-PR-Validation/5119/
http://10.239.47.210:18888/job/ZOO-PR-Python-integration-test/59/

**Comment by yangw1234** [comment]
LGTM

**Comment by jason-dai** [comment]
Move the examples to pyzoo/zoo/examples/ray_on_spark/

**Comment by leonardozcm** [comment]
> Move the examples to `pyzoo/zoo/examples/ray_on_spark/`

Sure, I will fixed it ASAP

**Pull request merged**
