### PR TITLE
Add transfer learning notebook

### PR DESCRIPTION
**Pull request by xuex2017**

### CODE REVIEW

**Comment by jason-dai** [comment]
1) Change the folder name to "dogs-vs-casts"
2) Change occurrence of "Zoo" to "Analytics Zoo"
3) Do not show the path specific to the user (e.g., "/home/xiaxu...")
4) Visualize some pictures for the final predictions (with both dogs and cats)

**Comment by xuex2017** [comment]
which folder's name should be changed to "dogs-vs-cat"?

**Comment by xuex2017** [comment]
Do you mean the "transfer-learning" folder be changed to "dogs-vs-cat"?

**Comment by jason-dai** [comment]
Yes, we should change the folder name.

**Pull request closed without merging**
