### PR TITLE
`load_orca_checkpoint` related updates for Orca BigDL / OpenVINO estimator

### PR DESCRIPTION
**Pull request by xiejinglei**
Remove `load_latest_orca_checkpoint` and modify `load_orca_checkpoint` to include the functionality of loading the latest checkpoint. Main modifications in this PR is related to Orca BigDL estimator.

There's also a minor update in the comment of orca pytorch estimator for consistency.

### CODE REVIEW

**Comment by xiejinglei** [comment]
It seems that there's currently no test for BigDL `load_orca_checkpoint`, shall we add a test maybe at [here](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/test/zoo/orca/learn/spark/test_estimator_for_bigdl.py) ? @yangw1234

**Comment by yangw1234** [comment]
Good catch!  Let's add a test here.

**Comment by xiejinglei** [comment]
Sorry I did not notice that `load_orca_checkpoint` of BigDL estimator is indirectly called in the test `test_xshards_spark_estimator`, so it may not be necessary to add an extra test currently... 

PR validation passed: http://10.239.47.210:18888/job/ZOO-PR-Validation/5271/

**Comment by yangw1234** [comment]
LGTM

**Pull request merged**
