### PR TITLE
Update XShards unique and len according to XShards [] selection support

### PR DESCRIPTION
**Pull request by jenniew**
Update unique() and __len__()  without 'key' parameter according to XShards selection with [] support

### CODE REVIEW

**Comment by jason-dai** [comment]
Please test the changes on the NCF example.

**Comment by cyita** [comment]
LGTM

**Comment by jenniew** [comment]
Update NCF Code: https://github.com/analytics-zoo/Mastercard-NCF/pull/13

**Comment by jenniew** [comment]
Jenkins Pass: http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/3633/

**Comment by jason-dai** [comment]
LGTM

**Pull request merged**
