### PR TITLE
move integration test to spark/yarn cluster

### PR DESCRIPTION
**Pull request by pinggao187**

### CODE REVIEW

**Comment by pinggao187** [comment]
fix [#4431](https://github.com/intel-analytics/analytics-zoo/issues/4431)

**Comment by pinggao187** [comment]
test
http://10.112.231.51:18888/view/ZOO-PR/job/ZOO-PR-scala-example-test/2/console

**Comment by pinggao187** [comment]
pass
http://10.112.231.51:18888/view/ZOO-PR/job/ZOO-PR-scala-example-test/3/

**Review by glorysdj — APPROVED** [review]
LGTM

**Pull request merged**
