### PR TITLE
Fix storage of Preprocessing objects in other filesystems

### PR DESCRIPTION
**Pull request by DVentas**
Unit Tests of this fix should be implemented mocking HDFS or other FileSystem. For now, this feature its not implemented in any test and do it in this fix its out of task scope. In a future it should be tested propertly.

### CODE REVIEW

**Comment by engapa** [comment]
This PR closes #1548

**Comment by jason-dai** [comment]
Thanks for the PR. @hhbyyh please take a look.

**Comment by hhbyyh** [comment]
Thanks for the fix @DVentas . I'll prepare a unit test later. Merging this after validation job.

**Comment by hhbyyh** [comment]
PR validation passed. Merging to master. Thanks for the fix.

**Pull request merged**
