### PR TITLE
Fix download URL in OpenVINO unit tests

### PR DESCRIPTION
**Pull request by qiyuangong**

### CODE REVIEW

**Comment by jason-dai** [comment]
Instead of disabling it, we should find a way to fix the error.

**Comment by qiyuangong** [comment]
OK. Will try to add a local storage.

**Comment by glorysdj** [comment]
please try this with new Jenkins PR job.

**Comment by glorysdj** [comment]
> please try this with new Jenkins PR job.

http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/3132/

**Comment by qiyuangong** [comment]
> > please try this with new Jenkins PR job.
> 
> http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/3132/

OK.

**Comment by qiyuangong** [comment]
Fix all unit tests, except one, which is caused by tensorflow issue (openvino optimizer). This issue is unable to solve until tensoflow fixing `'tensorflow.compat.v1' has no attribute 'pywrap_tensorflow'` on 1.13.0-1.14.

**Comment by qiyuangong** [comment]
Jenkins build passed http://10.239.47.210:18888/job/ZOO-PR-Validation/3148/

**Pull request merged**
