### PR TITLE
Change ray import folder structure

### PR DESCRIPTION
**Pull request by hkvision**
`from zoo.ray.util.raycontext import RayContex`t -> from `zoo.ray import RayContext`
Don't know why originally put this under ray.util, which is not handy for users to import.
@jason-dai

### CODE REVIEW

**Comment by hkvision** [comment]
jenkins passed http://10.239.47.210:18888/job/ZOO-PR-Validation/3201/

**Comment by hkvision** [comment]
@jason-dai Is it ok for the change?

**Comment by jason-dai** [comment]
LTGM

**Comment by hkvision** [comment]
RayContext in automl/README is not changed as @yushan111 would remove them in #2195

**Comment by hkvision** [comment]
http://10.239.47.210:18888/job/ZOO-PR-Validation/3209/ jenkins passed

**Pull request merged**
