### PR TITLE
Add gan example test

### PR DESCRIPTION
**Pull request by yangw1234**

### CODE REVIEW

**Comment by yangw1234** [comment]
@glorysdj @Le-Zheng can we merge this?

**Comment by Le-Zheng** [comment]
LGTM

**Comment by Le-Zheng** [comment]
http://10.239.47.211:18888/job/ZOO-PR-Python-ExampleTests-py35/160/
Success

**Comment by yangw1234** [comment]
I will first backport this to branch-0.7 and merge it to master once all container has upgraded up TF1.15

**Comment by yangw1234** [comment]
http://10.239.47.211:18888/view/ZOO-PR/job/ZOO-PR-Validation/2952/ jenkins pass on master

**Pull request merged**
