### PR TITLE
fix NNesimator apply

### PR DESCRIPTION
**Pull request by hhbyyh**

### CODE REVIEW

**Comment by hhbyyh** [comment]
cc @dding3 @jenniew for review. Thanks

**Comment by dding3** [comment]
LGTM

**Comment by hhbyyh** [comment]
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/477/ passed.

**Comment by hhbyyh** [comment]
Thanks for review. Merging to master.

**Pull request merged**
