### PR TITLE
bigdl 2.0 scala dllib and common construct

### PR DESCRIPTION
**Pull request by dding3**

### CODE REVIEW

**Comment by jason-dai** [comment]
Change the path `analytics-zoo/spark/dl/src/` to `analytics-zoo/scala/dllib/src/`

**Comment by dding3** [comment]
> Change the path `analytics-zoo/spark/dl/src/` to `analytics-zoo/scala/dllib/src/`

Can we update the path to bigdl/dllib/src/main/scala? as we also have some java code which defined some classes and needed be used by scala. Checked spark mllib path, it is `spark/mllib/src/main/scala/org/apache/spark/mllib`

**Comment by jason-dai** [comment]
> > Change the path `analytics-zoo/spark/dl/src/` to `analytics-zoo/scala/dllib/src/`
> 
> Can we update the path to bigdl/dllib/src/main/scala? as we also have some java code which defined some classes and needed be used by scala. Checked spark mllib path, it is `spark/mllib/src/main/scala/org/apache/spark/mllib`

Then how to you plan to add the python models? E.g., we will have both python dllib and scala dllib. One option is to put all python and scale modules under `bigdl/python` and `bigdl/scala` respectively; any other thoughts?

**Comment by dding3** [comment]
> > > Change the path `analytics-zoo/spark/dl/src/` to `analytics-zoo/scala/dllib/src/`
> > 
> > 
> > Can we update the path to bigdl/dllib/src/main/scala? as we also have some java code which defined some classes and needed be used by scala. Checked spark mllib path, it is `spark/mllib/src/main/scala/org/apache/spark/mllib`
> 
> Then how to you plan to add the python models? E.g., we will have both python dllib and scala dllib. One option is to put all python and scala modules under `bigdl/python` and `bigdl/scala` respectively; any other thoughts?

Maybe we can put all python modules under "pybigdl" and all scala modules under ""bigdl"? Checked spark, seems its python modules are put under "python" folder.

**Comment by jason-dai** [comment]
> > > > Change the path `analytics-zoo/spark/dl/src/` to `analytics-zoo/scala/dllib/src/`
> > > 
> > > 
> > > Can we update the path to bigdl/dllib/src/main/scala? as we also have some java code which defined some classes and needed be used by scala. Checked spark mllib path, it is `spark/mllib/src/main/scala/org/apache/spark/mllib`
> > 
> > 
> > Then how to you plan to add the python models? E.g., we will have both python dllib and scala dllib. One option is to put all python and scala modules under `bigdl/python` and `bigdl/scala` respectively; any other thoughts?
> 
> Maybe we can put all python modules under "pybigdl" and all scala modules under ""bigdl"? Checked spark, seems its python modules are put under "python" folder.

pybigdl is an awkward name; let's just use python and scala instead.

**Comment by dding3** [comment]
Close it as it's duplicate to https://github.com/intel-analytics/analytics-zoo/pull/4448

**Pull request closed without merging**
