### PR TITLE
Http serving merge

### PR DESCRIPTION
**Pull request by Gavin-Sun555**
Merge the new feature of cluster serving front end from Frontend2 to FrontendApp with the support of multi-model serving. Improve thread sleep mechanism and Akka at the same time. With tests, the performance is roughly the same as Frontend2.
Attached is test data comparing from the original Frontend App

On local Computer, Model Type DIEN.  Speed roughly improve 30%
Frontend Type | New Frontend App |  New Frontend App | Original Frontend App | Original Frontend App
-- | -- | -- | -- | -- 
Command | wrk -t1 -c1 -d30s  | wrk -t4 -c4 -d30s | wrk -t1 -c1 -d30s | wrk -t1 -c4 -d30s | wrk -t4 -c4 -d30s
wrk data | 122 ms | 450ms | 167ms | 608 ms

### CODE REVIEW

**Review by glorysdj — APPROVED** [review]
LGTM

**Comment by jason-dai** [comment]
Please add description of the new features and enhancements

**Review by Litchilitchy — APPROVED** [review]

**Comment by jason-dai** [comment]
> Merge the new feature of cluster serving front end from Frontend2 to FrontendApp with the support of multi-model serving. Improve thread sleep mechanism and Akka in the same time. With tests, the performance is roughly the same as Frontend2.

What's the performance improvement compared to the original FrontendApp?

**Comment by glorysdj** [comment]
> > Merge the new feature of cluster serving front end from Frontend2 to FrontendApp with the support of multi-model serving. Improve thread sleep mechanism and Akka in the same time. With tests, the performance is roughly the same as Frontend2.
> 
> What's the performance improvement compared to the original FrontendApp?

about 26.95% speedup according to yan's test data.

**Pull request merged**
