### PR TITLE
Expose Python model definition for TextClassifier

### PR DESCRIPTION
**Pull request by hkvision**
This Python version is workable and gets good accuracy after the training.

### CODE REVIEW

**Comment by hkvision** [comment]
jenkins passed http://10.239.47.211:18888/job/ZOO-PR-Validation/600/

**Comment by hkvision** [comment]
@jason-dai Have a review?

**Comment by hkvision** [comment]
jenkins passed http://10.239.47.211:18888/job/ZOO-PR-Validation/611/

**Comment by hkvision** [comment]
Manually run the example and the result is good.

**Comment by jason-dai** [comment]
LGTM

**Comment by hkvision** [comment]
Thanks for your review! Merged to master first. Embedding layer is WIP in another PR.

**Comment by hkvision** [comment]
jenkins passed http://10.239.47.211:18888/job/ZOO-PR-Validation/616/

**Comment by hkvision** [comment]
Running result:
```
2018-06-11 13:54:34 INFO  DistriOptimizer$:702 - [Epoch 20 15232/15154][Iteration 2380][Wall Clock 1656.077384455s] Validate model...
2018-06-11 13:54:41 INFO  DistriOptimizer$:744 - [Epoch 20 15232/15154][Iteration 2380][Wall Clock 1656.077384455s] Top1Accuracy is Accuracy(correct: 3151, count: 3674, accuracy: 0.8576483396842678)
```

**Pull request merged**
