### PR TITLE
Fix MXNet example download issue

### PR DESCRIPTION
**Pull request by hkvision**
http://10.239.47.210:18888/job/ZOO-PR-Python-ExampleTests-py36/439/console
Found the root cause of such random failure.
Two workers are downloading the data to the same location, as there is no something like lock, this would cause a problem.

### CODE REVIEW

**Comment by hkvision** [comment]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests/424/
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests/425/

**Comment by hkvision** [comment]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests/429/

**Comment by hkvision** [comment]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Validation/3231/ jenkins passed

**Comment by hkvision** [comment]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests/432/
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-ExampleTests/433/
Passed. Should have no problem.
Please contact me to fix this if random failure still occurs.

**Comment by qiuxin2012** [comment]
I just find ray has file lock to avoid the conflicting downloading. see https://docs.ray.io/en/latest/using-ray-with-pytorch.html#downloading-data for details.

**Comment by hkvision** [comment]
> I just find ray has file lock to avoid the conflicting downloading. see https://docs.ray.io/en/latest/using-ray-with-pytorch.html#downloading-data for details.

I would try this :)

**Pull request merged**
