### PR TITLE
update hyperzoo docker image

### PR DESCRIPTION
**Pull request by Le-Zheng**
to fix https://github.com/intel-analytics/analytics-zoo/issues/3428

### CODE REVIEW

**Comment by Le-Zheng** [comment]
Jenkins  http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Deploy-Docker/18/console

**Comment by dding3** [comment]
just out of curisority, why we didn't catch this exception https://github.com/intel-analytics/analytics-zoo/issues/3428 in our jekins?

**Comment by Le-Zheng** [comment]
> just out of curisority, why we didn't catch this exception #3428 in our jekins?

Jenkins job only tests building the image with Dockerfile successfully, not test jupyter running with the specified example. 
We have the plan to add Jenkins example tests with hyperzoo image on k8s.

**Comment by dding3** [comment]
> > just out of curisority, why we didn't catch this exception #3428 in our jekins?
> 
> Jenkins job only tests building the image with Dockerfile successfully, not test jupyter running with the specified example.
> We have the plan to add Jenkins example tests with hyperzoo image on k8s.

Thank you for the clarification. Can we manualy test if the fix works before we merge the PR. Just want to ensure the image we delivered worked.

**Comment by Le-Zheng** [comment]
> > > just out of curisority, why we didn't catch this exception #3428 in our jekins?
> > 
> > 
> > Jenkins job only tests building the image with Dockerfile successfully, not test jupyter running with the specified example.
> > We have the plan to add Jenkins example tests with hyperzoo image on k8s.
> 
> Thank you for the clarification. Can we manualy test if the fix works before we merge the PR. Just want to ensure the image we delivered worked.

Ok. give me commond/code. Let me have a try.

**Comment by Le-Zheng** [comment]
> > > > just out of curisority, why we didn't catch this exception #3428 in our jekins?
> > > 
> > > 
> > > Jenkins job only tests building the image with Dockerfile successfully, not test jupyter running with the specified example.
> > > We have the plan to add Jenkins example tests with hyperzoo image on k8s.
> > 
> > 
> > Thank you for the clarification. Can we manualy test if the fix works before we merge the PR. Just want to ensure the image we delivered worked.
> 
> Ok. give me commond/code. Let me have a try.



> > > just out of curisority, why we didn't catch this exception #3428 in our jekins?
> > 
> > 
> > Jenkins job only tests building the image with Dockerfile successfully, not test jupyter running with the specified example.
> > We have the plan to add Jenkins example tests with hyperzoo image on k8s.
> 
> Thank you for the clarification. Can we manualy test if the fix works before we merge the PR. Just want to ensure the image we delivered worked.

Run  `./start-notebook-k8s.sh`. It displays:
```
[I 2021-01-26 07:47:33.700 LabApp] JupyterLab extension loaded from /root/miniconda3/lib/python3.7/site-packages/jupyterlab
[I 2021-01-26 07:47:33.700 LabApp] JupyterLab application directory is /root/miniconda3/share/jupyter/lab
[I 07:47:33.704 NotebookApp] Serving notebooks from local directory: /opt/analytics-zoo-0.10.0-SNAPSHOT/apps
[I 07:47:33.704 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 07:47:33.704 NotebookApp] http://clx001:12345/?token=...
[I 07:47:33.704 NotebookApp]  or http://127.0.0.1:12345/?token=...
```

**Comment by dding3** [comment]
Thank you for the manual test. Can we try to run an example notebook to see if everything is ok, https://github.com/intel-analytics/analytics-zoo/blob/master/apps/automl/nyc_taxi_dataset.ipynb is good enough.

**Comment by Le-Zheng** [comment]
> Thank you for the manual test. Can we try to run an example notebook to see if everything is ok, run https://github.com/intel-analytics/analytics-zoo/blob/master/apps/automl/nyc_taxi_dataset.ipynb is good enough.

It works with the manual test. I merge it first.

**Pull request merged**
