### PR TITLE
Support redirecting jvm output to python process (when using notebook)

### PR DESCRIPTION
**Pull request by yangw1234**
Usage:
```python
from zoo import ZooContext, init_nncontext
ZooContext.log_output = True
sc = init_nncontext()  # or init_spark_on_local, init_spark_on_yarn
```
Then training logs will be printed to the current notebook.

image

Tested manually:

- [x] init_nncontext
- [x] init_spark_on_local
- [x] init_spark_on_yarn

### CODE REVIEW

**Comment by yangw1234** [comment]
A similar feature will be available in Spark 3.0

**Comment by jason-dai** [comment]
I think this is very useful @shane-huang 

Maybe it is better to set a global flag, instead of changing the function call? Or maybe set an env variable?

**Comment by yangw1234** [comment]
> I think this is very useful @shane-huang
> 
> Maybe it is better to set a global flag, instead of changing the function call? Or maybe set an env variable?

will change to an env variable.

**Comment by jason-dai** [comment]
> > I think this is very useful @shane-huang
> > Maybe it is better to set a global flag, instead of changing the function call? Or maybe set an env variable?
> 
> will change to an env variable.

Maybe add some global flag? such as `ZooContext.log_output`?

**Comment by yangw1234** [comment]
Hi @jason-dai , do you mean letting users set the flag before init_nncontext()? Such as:

```python
ZooContext.log_output = True
sc = init_nncontext()
```

**Comment by jason-dai** [comment]
> Hi @jason-dai , do you mean letting users set the flag before init_nncontext()? Such as:
> 
> ```python
> ZooContext.log_output = True
> sc = init_nncontext()
> ```

Yes

**Comment by yangw1234** [comment]
> > Hi @jason-dai , do you mean letting users set the flag before init_nncontext()? Such as:
> > ```python
> > ZooContext.log_output = True
> > sc = init_nncontext()
> > ```
> 
> Yes

changed to `ZooContext.log_output = True`

**Comment by jason-dai** [comment]
LGTM

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/3588/ jenkins passed

**Pull request merged**
