### PR TITLE
move pytorch trainer to sub folder

### PR DESCRIPTION
**Pull request by qiuxin2012**
move pytorch trainer to sub folder

### CODE REVIEW

**Comment by qiuxin2012** [comment]
@jason-dai Huangkai and I think using a sub folder is better to avoid importing unnessessary dependence.

**Comment by jason-dai** [comment]
> @jason-dai Huangkai and I think using a sub folder is better to avoid importing unnessessary dependence.

Can we just use separate files? And don't create additional module hierarchy like `zoo.orca.learn.pytorch.ray`

**Comment by hkvision** [comment]
> > @jason-dai Huangkai and I think using a sub folder is better to avoid importing unnessessary dependence.
> 
> Can we just use separate files? And don't create additional module hierarchy like `zoo.orca.learn.pytorch.ray`

Separating files and removing the import in init will lead to `from zoo.orca.learn.pytorch.pytorch_trainer import PyTorchTrainer`, this would be inconvenient?

**Comment by jason-dai** [comment]
> > > @jason-dai Huangkai and I think using a sub folder is better to avoid importing unnessessary dependence.
> > 
> > 
> > Can we just use separate files? And don't create additional module hierarchy like `zoo.orca.learn.pytorch.ray`
> 
> Separating files and removing the import in init will lead to `from zoo.orca.learn.pytorch.pytorch_trainer import PyTorchTrainer`, this would be inconvenient?

Maybe we can create separate files under `orca.learn`, such as pythorch.py, mxnet.py, tf.py,, etc., and put the corresponding estimator/trainer classes in the file, and import necessary modules only inside the classes.

**Pull request closed without merging**
