### PR TITLE
fix wide values in wide deep

### PR DESCRIPTION
**Pull request by qiuxin2012**
values in widemodel's input is incorrect, all the values is 1. the values should be indices for LookuptableSparse.

### CODE REVIEW

**Comment by jason-dai** [comment]
Shall we merge it @hkvision ?

**Comment by hkvision** [comment]
Yeah, still running jenkins. Will merge it after pr validation pass. @jason-dai

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/597/

**Comment by hkvision** [comment]
app tests passed http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Python-AppTests/63/

**Comment by hkvision** [comment]
Thanks so much for your contribution!

**Pull request merged**
