### PR TITLE
Refine Orca Pytorch Quickstart

### PR DESCRIPTION
**Pull request by GZHoffie**
Adjusted detail in Orca Pytorch Quickstart markdown and notebook according to comments in #3583.

### CODE REVIEW

**Comment by GZHoffie** [comment]
Jenkins passed here: http://10.239.47.210:18888/job/ZOO-PR-Quickstart-notebook/209/, readthedocs build was also successful.

**Review by hkvision — APPROVED** [review]
Thanks for the update.

**Comment by jason-dai** [comment]
Tyr to run the PyTorch quickstart, and ran into several issues:

1) For some reason MNIST website gives HTTP 503 errors when running torchvision.datasets.MNIST; see https://stackoverflow.com/questions/66646604/http-error-503-service-unavailable-whan-trying-to-download-mnist-data for a solution

2) Run training and got an JEP error `jep.JepException: <class 'SystemError'>: unknown opcode`

3) Don't combine two versions of code into a single notebook for BigDL backend. We should keep the quickstart simple. Instead, keep the original BigDL backend quickstart unchanged, and add a new notebook for using Data Creator Function with BigDL backend.

@yangw1234 @GZHoffie

**Comment by yangw1234** [comment]
> Tyr to run the PyTorch quickstart, and ran into several issues:
> 
> 1. For some reason MNIST website gives HTTP 503 errors when running torchvision.datasets.MNIST; see https://stackoverflow.com/questions/66646604/http-error-503-service-unavailable-whan-trying-to-download-mnist-data for a solution
> 2. Run training and got an JEP error `jep.JepException: <class 'SystemError'>: unknown opcode`
> 3. Don't combine two versions of code into a single notebook for BigDL backend. We should keep the quickstart simple. Instead, keep the original BigDL backend quickstart unchanged, and add a new notebook for using Data Creator Function with BigDL backend.
> 
> @yangw1234 @GZHoffie

The second error `jep.JepException: <class 'SystemError'>: unknown opcode` is probably becase colab upgrade the default python version to 3.7 and we install our packages in a conda env with python3.6.

**Comment by yangw1234** [comment]
@GZHoffie @Le-Zheng maybe we can detect the hosted python version and installed the same version in conda?

**Comment by Le-Zheng** [comment]
> @GZHoffie @Le-Zheng maybe we can detect the hosted python version and installed the same version in conda?

Ok. we need to get colab python version first. For example, we add `python_version = "{}.{}".format(sys.version_info.major, sys.version_info.minor)` , then make conda install the same python_version with host.

**Comment by GZHoffie** [comment]
> > @GZHoffie @Le-Zheng maybe we can detect the hosted python version and installed the same version in conda?
> 
> Ok. we need to get colab python version first. For example, we add `python_version = "{}.{}".format(sys.version_info.major, sys.version_info.minor)` , then make conda install the same python_version with host.

Got it, thanks. I will open a separate PR for the change.

**Pull request merged**
