### PR TITLE
orca.data.image.read_parquet support reading as pytorch dataloader

### PR DESCRIPTION
**Pull request by leonardozcm**
Related to #4012 
workflow:
1. read specified chunk pieces according to num_shards and rank, place them into memory.
2. make it iterable and return.

- [x] read parquet datasets' meta info
- [x] merging logic
- [x] dispatch code
- [x] uts
- [x] code style

### CODE REVIEW

**Comment by yangw1234** [comment]
Let's first implement a basic vesion that works, so that Le and the Inspur team can continue their work basing on it.

**Comment by leonardozcm** [comment]
Known issues here:
ray's multi-process processing may have conflicts with this dataloader, in which way may change the behavior of loading data to dataloader's dataqueue. Also this has something to do with init cores on spark.

- num_workers=0, local cores=N, looks fine
- num_workers=2, local cores=2, looks fine
- num_workers=2, local cores>2, meets segmentation fault.

**Comment by leonardozcm** [comment]
http://10.239.176.111:18888/job/ZOO-PR-Validation/5737/

**Comment by yangw1234** [comment]
Generally LGTM, l'll first merge this to prevent blocking inspur guys.

**Pull request merged**
