### PR TITLE
[Fix #4328]Repartition validation data for zip reduce RayXShards

### LINKED ISSUE #4328: RayXShards zip reduce shouldn't assume the same number of partitions for train and test data
https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/orca/data/ray_xshards.py#L232

Currently logic is:
- If train data partitions < num workers, we repartition to the number of workers. Otherwise the partition number will be unchanged.
- So if originally train rdd and test rdd have different partitions larger than the number of workers, the error "the rdds to be zipped must have the same number of partitions" will always occur.

We need to handle the partition issue by ourselves in our estimator.

### PR DESCRIPTION
**Pull request by yushan111**
This PR is to fix #4328

### CODE REVIEW

**Comment by yushan111** [comment]
@hkvision  
I repartition the `validatition_data` to the same partition number as `data`
Does that work for your issue?

**Comment by hkvision** [comment]
I think it is ok. But will repartition be expensive? Are there any better ways?

**Comment by yangw1234** [comment]
LGTM

**Review by yangw1234 — APPROVED** [review]

**Comment by yushan111** [comment]
> I think it is ok. But will repartition be expensive? Are there any better ways?

According to current design, repartition might be the most convenient way. We could enhance that in later PRs.

**Comment by yushan111** [comment]
http://10.239.176.111:18888/view/ZOO-PR/job/ZOO-PR-Validation/6127/

**Pull request merged**
