### PR TITLE
 remove import tensorflow from top of file

### PR DESCRIPTION
**Pull request by yangw1234**

### CODE REVIEW

**Comment by yangw1234** [comment]
manually tested
The following code works without tensorflow
```
from zoo.pipeline.api.net import Net

model = Net.load_bigdl("/home/yang/analytics-zoo_inception-v1_imagenet_0.1.0.model")
```

**Comment by hhbyyh** [comment]
LGTM.

about the parameter name, do you think we should change it batch_per_thread in all places? Either `batch_per_thread` and `batch_per_core` is good to me.

**Comment by yangw1234** [comment]
@hhbyyh I'll change them all to batch_per_thread

**Comment by yangw1234** [comment]
pr validation pass
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/1272/
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/1271/

**Pull request merged**
