### PR TITLE
update the message when setting log_output after init context and change it to a warning

### LINKED ISSUE #3365: LogOutput
It will throw an error if its called after SparkContext is created:
```
AttributeError: log_output cannot be set after SparkContext is created. Please set it before init_nncontext, init_spark_on_localor init_spark_on_yarn
```
1) The error message is not general. Change it to sth like "You need to set log_output before initializing the context (e.g., before calling init_orca_context, init_nncontext, etc.)

2) Shall we make it a warning or error?

### PR DESCRIPTION
**Pull request by yangw1234**
Fix #3365 
Change to something like this:
image

### CODE REVIEW

**Comment by jason-dai** [comment]
LGTM

**Comment by jason-dai** [comment]
https://github.com/intel-analytics/analytics-zoo/tree/master/readthedocs/source

**Comment by yangw1234** [comment]
> https://github.com/intel-analytics/analytics-zoo/tree/master/readthedocs/source

@jason-dai you mean changing the doc? 
The original description seems ok?

image

**Comment by jason-dai** [comment]
> > https://github.com/intel-analytics/analytics-zoo/tree/master/readthedocs/source
> 
> @jason-dai you mean changing the doc?
> The original description seems ok?
> 
> image

Yes

**Comment by yangw1234** [comment]
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/4940/ jenkins passed

**Pull request merged**
