### PR TITLE
remove CallBigDLFunc during import

### PR DESCRIPTION
**Pull request by hhbyyh**
Avoid creating the extra SparkContext during import.

more details in https://github.com/intel-analytics/zoo/issues/352#issue

### CODE REVIEW

**Comment by hkvision** [comment]
Thanks for your fix! :) LGTM
Would you mind adding an assert here https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/test/zoo/pipeline/nnframes/test_nn_classifier.py#L41 to make sure that the setting of AppName succeeds?

**Comment by hhbyyh** [comment]
cc @hkvision Can you help review this? Thanks.

**Comment by hkvision** [comment]
Feel free to merge it after adding unit test about sc

**Comment by hhbyyh** [comment]
http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Validation/884/ passed.

**Comment by hhbyyh** [comment]
Added the assert. Merging to master. Thanks for the review @hkvision .

**Pull request merged**
