### PR TITLE
Exclude dllib from orca jar

### PR DESCRIPTION
**Pull request by yushan111**
After removing `bigdl-dllib`, orca jar size reduces from 389M to 245M

Before:
```
-rw-rw-r-- 1 shan shan 152822343 9月  24 10:18 bigdl-dllib-0.14.0-SNAPSHOT-jar-with-dependencies.jar
-rw-rw-r-- 1 shan shan    600532 9月  24 10:18 bigdl-dllib-0.14.0-SNAPSHOT-python-api.zip
-rw-rw-r-- 1 shan shan 389080878 9月  24 10:18 bigdl-orca-0.14.0-SNAPSHOT-jar-with-dependencies.jar
-rw-rw-r-- 1 shan shan    708745 9月  24 10:18 bigdl-orca-0.14.0-SNAPSHOT-python-api.zip

```
After:
```
-rw-rw-r-- 1 shan shan 122773321 9月  26 17:09 bigdl-dllib-0.14.0-SNAPSHOT-jar-with-dependencies.jar
-rw-rw-r-- 1 shan shan    600529 9月  26 17:09 bigdl-dllib-0.14.0-SNAPSHOT-python-api.zip
-rw-rw-r-- 1 shan shan 245061252 9月  26 17:09 bigdl-orca-0.14.0-SNAPSHOT-jar-with-dependencies.jar
-rw-rw-r-- 1 shan shan    818616 9月  26 17:09 bigdl-orca-0.14.0-SNAPSHOT-python-api.zip

```

### CODE REVIEW

**Comment by yushan111** [comment]
Running Jenkins:

python:
http://10.112.231.51:18888/view/ZOO-PR/job/ZOO-PR-Validation-BigDL-2.0/2/

**Comment by jason-dai** [comment]
Why is it much larger than Analytics Zoo today?

**Comment by yushan111** [comment]
> Why is it much larger than Analytics Zoo today?

Orca jar includes `zoo-core-dist-all` while zoo has profile `linux` and `mac`, with which analytics zoo jar only includes `zoo-core-dist-linux64` or `zoo-core-dist-mac`. 
I have changed orca pom respectively. And orca jar size decreased to 130M with `-P linux`.

**Comment by yushan111** [comment]
Excluding `dllib` for orca jar introduces compile failure in building `bigdl-serving` jar. I didn't find a direct way to solve it.
Error message in building `bigdl-serving` jar:
```
[ERROR] /opt/work/jenkins/workspace/BigDL-PRVN-pythontest-Spark-3.1/scala/serving/src/main/scala/com/intel/analytics/bigdl/serving/engine/ClusterServingInference.scala:20: object dllib is not a member of package com.intel.analytics.bigdl
[ERROR] import com.intel.analytics.bigdl.dllib.nn.abstractnn.Activity
[ERROR]                                  ^
```

Result:
```
[ERROR] 111 errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for BigDL 0.14.0-SNAPSHOT:
[INFO] 
[INFO] BigDL .............................................. SUCCESS [  1.078 s]
[INFO] spark-version ...................................... SUCCESS [  0.177 s]
[INFO] 3.0 ................................................ SUCCESS [  8.655 s]
[INFO] bigdl-dllib ........................................ SUCCESS [03:08 min]
[INFO] bigdl-orca ......................................... SUCCESS [ 58.481 s]
[INFO] bigdl-serving ...................................... FAILURE [  2.648 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:20 min
[INFO] Finished at: 2021-09-27T06:35:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.4.2:compile (scala-compile-first) on project bigdl-serving: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.4.2:compile failed.: CompileFailed -> [Help 1]
```

I will close this PR and might solve the problem in new PR.

**Pull request closed without merging**
