### PR TITLE
Fix XGBoost fit_eval use mean validation result instead of final validation result

### PR DESCRIPTION
**Pull request by PeterQiu0516**
Fix issue #3720.
Return validation result of last iteration.

### CODE REVIEW

**Comment by yushan111** [comment]
We shouldn't include the commits from other branches. 

Before create a PR, we should always update the upstream master and checkout a new branch from it. Several commands for your reference.

```bash 
git checkout master (upsteam master)
git pull 
git checkout -b my-pr
```

**Comment by yushan111** [comment]
To fix that, one option is to 
``` bash 
## on branch fix-XGBoost-eval-mean
git checkout -b fix-XGBoost-eval-mean-bk
git checkout fix-XGBoost-eval-mean
git fetch master 
git reset master --hard 
git cherry-pick commit-ids-on-fix-XGBoost-eval-mean-bk
git push -f 
```
Just for your reference and there should be other better options.

**Comment by PeterQiu0516** [comment]
Resolved! Running PR validation now.

**Comment by PeterQiu0516** [comment]
Jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation/5321/

**Comment by dding3** [comment]
LGTM

**Comment by PeterQiu0516** [comment]
Jenkins passed: http://10.239.47.210:18888/job/ZOO-PR-Validation/5356/

**Pull request merged**
