### PR TITLE
Add ray daemon to kill ray processes

### PR DESCRIPTION
**Pull request by yushan111**
## What is this PR for? 
While running `RayOnSpark` in cluster, if the spark executor is killed abruptly (e.g. killed by yarn due to memory-deficiency), the ray processes will keep running until meet further error (e.g "No module named zoo"). However, the ray processes should be killed immediately if the spark executor died. 

## Related issue
#4425 

## What does this PR include? 

1. This PR added a ray daemon to watch spark executor and kill ray processes after the spark executor is died.
2. This PR removes `shutdown_hook` and `clean_fn` in `ProcessMonitor` which are also for killing ray processes. And the functions don't work at all circumstances, such as `core_dump`.

## How is this PR tested? 
This PR has only been tested on **Linux**.
In both "standalone" mode and "yarn-client" mode:

- [x] exit normally
- [x] exit with errors which occur at different stages
- [x] interrupted with Ctrl + C 
- [x] kill -9 spark executor
- [x] kill -9 driver

In "yarn-client" mode, "core dump" after ray initialized has also been tested.

## Remained issue
1. Application keeps running after one spark executor is killed abruptly, since the processes on other nodes are not influenced. 
2. Test on MAC/Win
3. Better debug log for `ray_daemon`

### CODE REVIEW

**Comment by hkvision** [comment]
Generally LGTM.

**Comment by hkvision** [comment]
1. Shall we put your test scripts somewhere as a backup?
2. If one spark executor dies, only the raylet combined with that executor will be killed right? So what if a new executor is relaunched by spark? the number of executors and the number of raylets will be different in this case?

**Comment by yushan111** [comment]
>Shall we put your test scripts somewhere as a backup?

Actually the test script is pretty simple. I just added some `time.sleep` to ensure I could interrupt or kill the executor before the application finished.  The tests are mostly manually, like `ctrl + C` or `kill -9`. I could add the test script in repo like `test/zoo/ray/integration/` and disable the auto-test for back up. Or are there other places recommended?

**Comment by yushan111** [comment]
>If one spark executor dies, only the raylet combined with that executor will be killed right? So what if a new executor is relaunched by spark? the number of executors and the number of raylets will be different in this case?

The right behavior might be if one spark executor dies, we shouldn't allow any retries and just make the whole application terminate. Because even though a new spark executor is relaunched, it is not associated with any ray actors so our `RayOnSpark` just doesn't work as expected.  In case of this PR, spark will relaunch executors until the max failure is reached. and it will take a long time.

As mentioned in the first remained issue, we could open another PR to terminate the whole application at the time one spark executor dies. To be honest, I haven't come up with a good solution for that yet. I tried modifying some spark confs listed in [comment](https://github.com/intel-analytics/analytics-zoo/pull/4571#issuecomment-911416426), and it disables retry. But it might be too strict.

**Comment by hkvision** [comment]
> > Shall we put your test scripts somewhere as a backup?
> 
> Actually the test script is pretty simple. I just added some `time.sleep` to ensure I could interrupt or kill the executor before the application finished. The tests are mostly manually, like `ctrl + C` or `kill -9`. I could add the test script in repo like `test/zoo/ray/integration/` and disable the auto-test for back up. Or are there other places recommended?

So put it in `test/zoo/ray/integration/` and add some simple README in case to reproduce it later?

**Comment by hkvision** [comment]
> As mentioned in the first remained issue, we could open another PR to terminate the whole application at the time one spark executor dies. To be honest, I haven't come up with a good solution for that yet. I tried modifying some spark confs listed in [comment](https://github.com/intel-analytics/analytics-zoo/pull/4571#issuecomment-911416426), and it disables retry. But it might be too strict.

It is reasonable to terminate the whole application when one spark executor dies. We may discuss whether we need to do this later.

**Comment by yushan111** [comment]
I will merge this PR and add test scripts/solve the remained issues in new PRs.

**Comment by yushan111** [comment]
Jenkins: http://10.112.231.51:18888/view/ZOO-PR/job/ZOO-PR-Validation/6425/

**Pull request merged**
