### PR TITLE
Add Keras Doc by Xinqi

### PR DESCRIPTION
**Pull request by cynthia-liu**

### CODE REVIEW

**Comment by cynthia-liu** [comment]
./GRU.scala
./Merge.scala
./SReLU.scala
./Squeeze.scala
./WithinChannelLRN2D.scala
./BinaryThreshold.scala
./Sqrt.scala
./HardTanh.scala
./ZeroPadding3D.scala
./MulConstant.scala
./AtrousConvolution2D.scala
./Scale.scala
./Activation.scala
./ThresholdedReLU.scala
./AveragePooling2D.scala
./ZeroPadding1D.scala
./SimpleRNN.scala
./Log.scala
./Identity.scala
./LRN2D.scala

**Comment by cynthia-liu** [comment]
@glorysdj

**Comment by cynthia-liu** [comment]
ZOO-PR-Validation - Build # 1560 - Successful:

Check console output at http://10.239.47.211:18888/job/ZOO-PR-Validation/1560/ to view the results.

The pull request: https://github.com/intel-analytics/analytics-zoo/pull/1025 Successful

**Comment by glorysdj** [comment]
LGTM

**Pull request merged**
