### PR TITLE
Check license for python files

### PR DESCRIPTION
**Pull request by hkvision**
Fix https://github.com/intel-analytics/zoo/issues/234
@dding3 Please have a review. Thanks~

### CODE REVIEW

**Comment by hkvision** [comment]
If no license or wrong license, jenkins will fail: http://172.168.2.101:8080/job/ZOO-PR-Python-Spark-2.2-py35/451/console

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/job/ZOO-PR-Validation/449/

**Comment by dding3** [comment]
LGTM

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/job/ZOO-PR-Validation/458/
Thanks for your review!

**Pull request merged**
